name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:
    name: .NET Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'
      
      # Prevents Kestrel from crashing on HTTPS bindings
      - name: Generate .NET dev cert
        run: |
          dotnet dev-certs https
          sudo mkdir -p /usr/local/share/ca-certificates/aspnet
          sudo -E dotnet dev-certs https -ep /usr/local/share/ca-certificates/aspnet/https.crt --format PEM
          sudo update-ca-certificates

      - run: dotnet build PlaylistApp.slnx -c Release
      - working-directory: ./PlaylistApp.Tests.Integration
        # Added the logger flag to expose background crash traces
        run: dotnet test -c Release --no-build --no-restore --logger "console;verbosity=normal"
  
  frontend:
    name: React Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: 'PlaylistApp.Web/package-lock.json'
      - working-directory: ./PlaylistApp.Web
        run: npm ci
      - working-directory: ./PlaylistApp.Web
        run: npm test -- --run
      - working-directory: ./PlaylistApp.Web
        run: npm run build